import type { DoorwayDefinition, InteractiveObjectDef, RoomDefinition } from './types';
import { getObjectAsset } from './assets/objectAppearance';

export const WORLD_WIDTH = 1280;
export const WORLD_HEIGHT = 880;

export const DOORWAYS: DoorwayDefinition[] = [
  {
    id: 'door_meeting_plaza',
    name: 'Conference Hub ↔ Central Plaza Portal',
    fromRoom: 'meeting',
    toRoom: 'lobby',
    x: 576,
    y: 424,
    width: 128,
    height: 32,
    clearanceBox: { x: 576, y: 352, width: 128, height: 176 },
  },
  {
    id: 'door_prog_meeting',
    name: 'Code Lab ↔ Conference Hub Portal',
    fromRoom: 'programming',
    toRoom: 'meeting',
    x: 416,
    y: 192,
    width: 32,
    height: 96,
    clearanceBox: { x: 344, y: 192, width: 176, height: 96 },
  },
  {
    id: 'door_art_meeting',
    name: 'Art Studio ↔ Conference Hub Portal',
    fromRoom: 'art',
    toRoom: 'meeting',
    x: 832,
    y: 192,
    width: 32,
    height: 96,
    clearanceBox: { x: 760, y: 192, width: 176, height: 96 },
  },
  {
    id: 'door_design_plaza',
    name: 'Design Bay ↔ Central Plaza Portal',
    fromRoom: 'design',
    toRoom: 'lobby',
    x: 416,
    y: 608,
    width: 32,
    height: 96,
    clearanceBox: { x: 344, y: 608, width: 176, height: 96 },
  },
  {
    id: 'door_audio_plaza',
    name: 'Audio Studio ↔ Central Plaza Portal',
    fromRoom: 'audio',
    toRoom: 'lobby',
    x: 832,
    y: 608,
    width: 32,
    height: 96,
    clearanceBox: { x: 760, y: 608, width: 176, height: 96 },
  },
  {
    id: 'door_prog_design',
    name: 'Code Lab ↔ Design Bay Concourse',
    fromRoom: 'programming',
    toRoom: 'design',
    x: 160,
    y: 424,
    width: 96,
    height: 32,
    clearanceBox: { x: 160, y: 352, width: 96, height: 176 },
  },
  {
    id: 'door_art_audio',
    name: 'Art Studio ↔ Audio Studio Concourse',
    fromRoom: 'art',
    toRoom: 'audio',
    x: 1024,
    y: 424,
    width: 96,
    height: 32,
    clearanceBox: { x: 1024, y: 352, width: 96, height: 176 },
  },
];

export const ROOMS: RoomDefinition[] = [
  {
    id: 'room_programming',
    type: 'programming',
    name: 'Engineering & Code Lab',
    color: 0x10192a,
    x: 32,
    y: 32,
    width: 384,
    height: 392,
    description: 'Core engine architecture, gameplay systems, network synchronization, and build servers.',
  },
  {
    id: 'room_meeting',
    type: 'meeting',
    name: 'Conference & Strategy Hub',
    color: 0x24170f,
    x: 448,
    y: 32,
    width: 384,
    height: 392,
    description: 'Central collaborative space for cross-discipline sprint syncs, presentation screen, and milestone reviews.',
  },
  {
    id: 'room_art',
    type: 'art',
    name: 'Art & Animation Studio',
    color: 0x1e1229,
    x: 864,
    y: 32,
    width: 384,
    height: 392,
    description: 'Concept art, character sprites, animation timelines, lighting, and environmental assets.',
  },
  {
    id: 'room_design',
    type: 'design',
    name: 'Game Design & Narrative Bay',
    color: 0x0d221c,
    x: 32,
    y: 456,
    width: 384,
    height: 392,
    description: 'Game balancing, narrative dialogue trees, progression curves, and playtest arcade.',
  },
  {
    id: 'room_lobby',
    type: 'lobby',
    name: 'Central Plaza & Lobby',
    color: 0x18202c,
    x: 448,
    y: 456,
    width: 384,
    height: 392,
    description: 'Central studio hub connecting all development departments, sprint milestones, and directories.',
  },
  {
    id: 'room_audio',
    type: 'audio',
    name: 'Audio & Sound Studio',
    color: 0x1f1430,
    x: 864,
    y: 456,
    width: 384,
    height: 392,
    description: 'Dynamic music stems, sound effects production, Foley recording, mixing, and listening lounge.',
  },
];

const objects: Omit<InteractiveObjectDef, 'width' | 'height'>[] = [
  // Central Plaza & Lobby (Studio Hub)
  {
    id: 'obj_room_layout_lobby',
    name: 'Console Pengatur Ruangan (Lobby)',
    type: 'room_layout',
    x: 485,
    y: 785,
    roomType: 'lobby',
    title: 'Konsol Penataan Ruangan — Central Plaza',
    description: 'Atur posisi furniture, putar arah 4 orientasi (0°, 90°, 180°, 270°), dan kunci layout ruangan.',
    actionText: 'Atur Layout Ruangan',
  },
  {
    id: 'obj_studio_directory',
    name: 'Studio Navigation Directory',
    type: 'studio_directory',
    x: 505,
    y: 485,
    roomType: 'lobby',
    title: 'Peta & Direktori Studio',
    description: 'Papan panduan navigasi denah spasial ke seluruh ruangan virtual studio.',
    actionText: 'Buka Direktori Ruangan',
  },
  {
    id: 'obj_plaza_project_status',
    name: 'Master Project Status Terminal',
    type: 'plaza_project_status',
    x: 505,
    y: 550,
    roomType: 'lobby',
    title: 'Ringkasan Cepat Status Proyek',
    description: 'Terminal status sprint dan milestone aktif proyek studio.',
    actionText: 'Lihat Status Proyek',
    plazaProjectStatusData: {
      projectName: 'Cyberpunk Odyssey: Protocol Zero',
      milestone: 'Milestone 2 — Core Combat & Alpha Playtest',
      overallProgress: 76,
      blockedCount: 2,
      waitingReviewCount: 4,
      activeSprint: 'Sprint 14',
      daysRemainingInSprint: 4,
      topPriorityGoal: 'Penyelesaian deteksi tabrakan 2D tanpa celah dan sinkronisasi audio dynamic combat loop',
      quickMetrics: [
        { label: 'Sprint Velocity', value: '92%' },
        { label: 'Build Pass Rate', value: '99.4%' },
        { label: 'Open PRs', value: '5 Pending' },
        { label: 'Playtesters', value: '12 Internal' },
      ],
    },
  },
  {
    id: 'obj_announcement_board',
    name: 'Studio Bulletin & Announcements',
    type: 'announcement_board',
    x: 775,
    y: 485,
    roomType: 'lobby',
    title: 'Papan Pengumuman Studio',
    description: 'Pemberitahuan milestone, jadwal playtest internal, dan info penting tim.',
    contextBubble: 'Pengumuman Baru: Jadwal Alpha Playtest & Evaluasi Sprint',
    actionText: 'Buka Pengumuman Studio',
  },
  {
    id: 'obj_team_presence_board',
    name: 'Studio Team Presence Board',
    type: 'team_presence',
    x: 775,
    y: 550,
    roomType: 'lobby',
    title: 'Papan Kehadiran Tim',
    description: 'Daftar aktivitas, ruangan, dan status kehadiran seluruh anggota tim studio.',
    contextBubble: 'Presensi Langsung: 5 Departemen aktif bekerja di studio',
    actionText: 'Lihat Kehadiran Tim',
  },
  {
    id: 'obj_plaza_wayfinding_sign',
    name: 'Wayfinding Signpost',
    type: 'studio_directory',
    x: 580,
    y: 590,
    roomType: 'lobby',
    title: 'Tiang Penunjuk Arah Ruangan',
    description: 'Petunjuk arah fisik menuju Programming, Art, Design, Audio, Meeting, dan Future QA.',
    contextBubble: 'Navigasi: Akses cepat ke 5 departemen & Conference Hub',
    actionText: 'Periksa Arah Ruangan',
  },
  {
    id: 'obj_plaza_lounge_bench_left',
    name: 'Central Plaza Lounge Bench (North)',
    type: 'desk',
    x: 745,
    y: 755,
    roomType: 'lobby',
    title: 'Bangku Santai Plaza (Sayap Utara Lounge)',
    description: 'Area duduk santai di pusat plaza untuk istirahat dan berkumpul.',
    contextBubble: 'Lounge Utara: Tempat duduk santai & ngobrol bersama tim',
    actionText: 'Duduk di Bangku Santai',
  },
  {
    id: 'obj_plaza_lounge_bench_right',
    name: 'Central Plaza Lounge Bench (South)',
    type: 'desk',
    x: 745,
    y: 800,
    roomType: 'lobby',
    title: 'Bangku Santai Plaza (Sayap Selatan Lounge)',
    description: 'Area duduk santai di pusat plaza untuk istirahat dan berkumpul.',
    contextBubble: 'Lounge Selatan: Diskusi santai dan koordinasi cepat',
    actionText: 'Duduk di Bangku Santai',
  },
  {
    id: 'obj_plaza_coffee_bar',
    name: 'Plaza Coffee & Conversation Bar',
    type: 'coffee',
    x: 495,
    y: 765,
    roomType: 'lobby',
    title: 'Bar Kopi & Obrolan Santai',
    description: 'Espresso hangat dan dispenser air untuk obrolan santai antar anggota tim.',
    contextBubble: 'Bar Kopi: Rehat sejenak & pulihkan stamina tim ☕',
    actionText: 'Ambil Kopi / Ngobrol',
  },
  {
    id: 'obj_future_qa_portal',
    name: 'Future QA Lab Corridor',
    type: 'board',
    x: 640,
    y: 832,
    roomType: 'lobby',
    title: 'Gerbang Rencana QA Lab',
    description: 'Akses masa depan menuju lab Quality Assurance dan pengujian kompatibilitas build (Sprint 16).',
    contextBubble: 'Rencana QA Lab: Pengujian otomatisasi & build verification (Sprint 16)',
    actionText: 'Periksa Info Rencana QA',
  },
  {
    id: 'obj_plant_lobby_nw',
    name: 'Potted Ficus (Plaza NW)',
    type: 'plant',
    x: 470,
    y: 500,
    roomType: 'lobby',
    title: 'Tanaman Hias Plaza (Barat Laut)',
    description: 'Tanaman ficus hias untuk menambah estetika dan kesegaran ruang plaza.',
    actionText: 'Lihat Tanaman Hias',
  },
  {
    id: 'obj_plant_lobby_ne',
    name: 'Potted Ficus (Plaza NE)',
    type: 'plant',
    x: 810,
    y: 500,
    roomType: 'lobby',
    title: 'Tanaman Hias Plaza (Timur Laut)',
    description: 'Tanaman ficus hias untuk menambah estetika dan kesegaran ruang plaza.',
    actionText: 'Lihat Tanaman Hias',
  },
  {
    id: 'obj_plant_lobby_sw',
    name: 'Potted Palm (Plaza SW)',
    type: 'plant',
    x: 470,
    y: 810,
    roomType: 'lobby',
    title: 'Tanaman Palem Plaza (Barat Daya)',
    description: 'Tanaman palem indoor untuk menyegarkan suasana lounge.',
    actionText: 'Lihat Tanaman Palem',
  },
  {
    id: 'obj_plant_lobby_se',
    name: 'Potted Palm (Plaza SE)',
    type: 'plant',
    x: 810,
    y: 810,
    roomType: 'lobby',
    title: 'Tanaman Palem Plaza (Tenggara)',
    description: 'Tanaman palem indoor untuk menyegarkan suasana lounge.',
    actionText: 'Lihat Tanaman Palem',
  },

  // Programming Room - Engineering & Code Lab Workstations
  {
    id: 'obj_room_layout_programming',
    name: 'Console Pengatur Ruangan (Code Lab)',
    type: 'room_layout',
    x: 75,
    y: 75,
    roomType: 'programming',
    title: 'Konsol Penataan Ruangan — Engineering & Code Lab',
    description: 'Atur posisi furniture, putar arah 4 orientasi (0°, 90°, 180°, 270°), dan kunci layout ruangan.',
    actionText: 'Atur Layout Ruangan',
  },
  {
    id: 'obj_workstation_alex',
    name: 'Workstation 1 — Alex Rivera',
    type: 'monitor',
    x: 130,
    y: 105,
    roomType: 'programming',
    title: 'Lead Physics & Engine Workstation',
    description: 'Lead dev workstation running continuous physics tuning and collision solvers.',
    actionText: 'Inspect Alex Rivera',
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Alex Rivera',
      discipline: 'Programmer',
      roleTitle: 'Physics & Engine Lead',
      isAssigned: true,
      assignedUserId: 'colleague_alex',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Deterministic 2D collision resolution and client-side prediction',
      progressPercentage: 75,
      status: 'In Flow',
      currentTaskTitle: 'Tuning Phaser Arcade Physics body offsets and velocity clamps',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'GitHub PR #42 — Deterministic 2D Physics Pipeline',
        url: 'https://github.com/example/engine/pull/42',
      },
    },
  },
  {
    id: 'obj_workstation_maya',
    name: 'Workstation 2 — Maya Chen',
    type: 'monitor',
    x: 240,
    y: 105,
    roomType: 'programming',
    title: 'Graphics & Gameplay Workstation',
    description: 'Dev terminal setup for 2D lighting shaders and character animation pacing.',
    actionText: 'Inspect Maya Chen',
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Maya Chen',
      discipline: 'Programmer',
      roleTitle: 'Gameplay & Shaders Specialist',
      isAssigned: true,
      assignedUserId: 'colleague_maya',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Dynamic pixel lighting pass and interaction proximity rings',
      progressPercentage: 60,
      status: 'Pair Programming',
      currentTaskTitle: 'Procedural canvas texture generation and sprite frame pacing',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Branch: feature/lighting-shaders',
        url: 'https://github.com/example/engine/tree/feature/lighting-shaders',
      },
    },
  },
  {
    id: 'obj_workstation_liam',
    name: 'Workstation 3 — Liam Vance',
    type: 'monitor',
    x: 130,
    y: 220,
    roomType: 'programming',
    title: 'Networking & Realtime Workstation',
    description: 'Multiplayer synchronization station (assigned to Liam Vance, currently offline).',
    actionText: 'Inspect Liam Vance (Offline)',
    workstationStatus: 'assigned_offline',
    workstationData: {
      name: 'Liam Vance',
      discipline: 'Programmer',
      roleTitle: 'Realtime Sync & State Architect',
      isAssigned: true,
      assignedUserId: 'colleague_liam',
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Throttled player presence broadcasts & smooth remote interpolation',
      progressPercentage: 90,
      status: 'Reviewing PR',
      currentTaskTitle: 'WebSocket delta compression and latency compensation',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'GitHub PR #39 — Realtime Channel Broadcasts',
        url: 'https://github.com/example/engine/pull/39',
      },
    },
  },
  {
    id: 'obj_workstation_flex',
    name: 'Workstation 4 — Flex Desk',
    type: 'monitor',
    x: 240,
    y: 220,
    roomType: 'programming',
    title: 'Available Hotdesk / Flex Station',
    description: 'Open developer desk available for any team member, guest, or immediate focus session.',
    actionText: 'Use Available Desk',
    workstationStatus: 'available',
    workstationData: {
      name: 'Available (Flex Station)',
      discipline: 'Programmer',
      roleTitle: 'Open Hotdesk Station',
      isAssigned: false,
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Open for assignment or immediate coding session',
      progressPercentage: 0,
      status: 'Idle',
      currentTaskTitle: 'Station ready for check-in',
      seatOffset: { x: 0, y: 19 },
    },
  },
  {
    id: 'obj_server_rack',
    name: 'CI/CD Build Server Rack',
    type: 'monitor',
    x: 75,
    y: 160,
    roomType: 'programming',
    title: 'Studio Build Cluster',
    description: 'Automated artifact packaging, unit testing suites, and git deployment pipeline.',
    actionText: 'Check Server Health',
    workstationData: {
      name: 'Studio Build Cluster',
      discipline: 'Programmer',
      roleTitle: 'Automated Pipeline Daemon',
      isAssigned: true,
      currentGoal: 'Continuous build verification & artifact compilation pipeline',
      progressPercentage: 100,
      status: 'Building',
      currentTaskTitle: 'Compiling Vite bundle: dist/assets/index.js',
      externalWorkLink: {
        label: 'Cluster Diagnostics & Deployment Log',
        url: 'https://ci.example-studio.internal/pipeline',
      },
    },
  },
  {
    id: 'obj_code_whiteboard',
    name: 'System Architecture Board',
    type: 'board',
    x: 345,
    y: 85,
    roomType: 'programming',
    title: 'Engine Systems Architecture',
    description: 'Core game loop, decoupled Phaser-React event bridge, and physics subsystem flowcharts.',
    actionText: 'Review Architecture Blueprint',
  },
  {
    id: 'obj_water_cooler',
    name: 'Code Lab Hydro Station',
    type: 'coffee',
    x: 365,
    y: 140,
    roomType: 'programming',
    title: 'Dev Hydro Cooler',
    description: 'Cold water dispenser for programmers fixing late-night memory leaks.',
    actionText: 'Drink Cold Water',
  },
  {
    id: 'obj_shared_shelf_prog',
    name: 'Engineering Reference Shelf',
    type: 'decoration',
    x: 100,
    y: 330,
    roomType: 'programming',
    title: 'Rak Buku & Referensi Rekayasa',
    description: 'Rak buku berisi dokumentasi arsitektur sistem, algoritma, dan buku teknis pemrograman.',
    actionText: 'Periksa Rak Buku',
  },
  {
    id: 'obj_plant_prog',
    name: 'Code Lab Plant',
    type: 'plant',
    x: 55,
    y: 55,
    roomType: 'programming',
    title: 'Tanaman Hias Code Lab',
    description: 'Tanaman hias indoor untuk menyegarkan udara ruang rekayasa perangkat lunak.',
    actionText: 'Lihat Tanaman',
  },

  // Art Room — Dedicated Visual Production Studio
  {
    id: 'obj_room_layout_art',
    name: 'Console Pengatur Ruangan (Art Studio)',
    type: 'room_layout',
    x: 1205,
    y: 75,
    roomType: 'art',
    title: 'Konsol Penataan Ruangan — Art & Animation Studio',
    description: 'Atur posisi furniture, putar arah 4 orientasi (0°, 90°, 180°, 270°), dan kunci layout ruangan.',
    actionText: 'Atur Layout Ruangan',
  },
  {
    id: 'obj_moodboard_wall',
    name: 'Reference Wall & Moodboard',
    type: 'moodboard',
    x: 1060,
    y: 65,
    roomType: 'art',
    title: 'Studio Art Reference Wall',
    description: 'Central pinboard featuring color scripts, lighting swatches, character silhouette pins, and architecture moodboards.',
    actionText: 'Open Moodboard & References',
    moodboardItems: [
      {
        id: 'mb_1',
        title: 'Neon Cyberpunk Lighting Script',
        category: 'Lighting',
        colorAccent: '#38bdf8',
        description: 'High-contrast cyan and magenta wash contrasting against dark slate flooring with sharp floor cutouts.',
        tags: ['lighting', 'neon', 'ambient'],
        externalUrl: 'https://figma.com/@studio/lighting-script',
      },
      {
        id: 'mb_2',
        title: 'Main Character Silhouette Turnaround',
        category: 'Characters',
        colorAccent: '#ec4899',
        description: 'Clean readable 32x32 pixel silhouette with distinct head, shoulders, directional eye cues, and walking feet.',
        tags: ['character', 'turnaround', 'pixelart'],
        externalUrl: 'https://figma.com/@studio/character-silhouettes',
      },
      {
        id: 'mb_3',
        title: 'Department Floor Color Accents',
        category: 'Environment',
        colorAccent: '#a855f7',
        description: 'Color-coded floor borders: Blue for Code, Violet for Art, Emerald for Design, Amber for Review.',
        tags: ['palette', 'navigation', 'rooms'],
        externalUrl: 'https://figma.com/@studio/room-palettes',
      },
      {
        id: 'mb_4',
        title: 'VFX Pulse & Bloom Guidelines',
        category: 'VFX',
        colorAccent: '#10b981',
        description: 'Subtle interaction pulse rings with 600ms ease-in-out breathing cycle and glowing borders.',
        tags: ['vfx', 'shaders', 'polish'],
        externalUrl: 'https://figma.com/@studio/vfx-guidelines',
      },
    ],
  },
  {
    id: 'obj_art_review_board',
    name: 'Shared Art Review Board',
    type: 'art_review',
    x: 935,
    y: 75,
    roomType: 'art',
    title: 'Production Art Review Pipeline',
    description: 'Shared review board tracking character turnarounds, environment tiles, and VFX shaders awaiting critique or approval.',
    actionText: 'Open Review Board',
    reviewItems: [
      {
        id: 'rev_1',
        assetName: 'Player Character 4-Dir Walk Frames',
        ownerName: 'Kenji Sato',
        category: 'Character',
        reviewState: 'pending',
        progressPercentage: 80,
        feedbackNotes: 'Feet movement looks smooth. Ensure right-facing eye maintains 1px gap from brow line.',
        externalAssetUrl: 'https://figma.com/@studio/assets/player-walk',
      },
      {
        id: 'rev_2',
        assetName: 'Cyberpunk Server Rack & Terminal',
        ownerName: 'Clara Oswald',
        category: 'Environment',
        reviewState: 'approved',
        progressPercentage: 100,
        feedbackNotes: 'Color palette matches the programming lab perfectly. Approved for V1.',
        externalAssetUrl: 'https://figma.com/@studio/assets/server-rack',
      },
      {
        id: 'rev_3',
        assetName: 'Neon Interaction Pulse Ring',
        ownerName: 'Marcus Vance',
        category: 'VFX',
        reviewState: 'changes_requested',
        progressPercentage: 90,
        feedbackNotes: 'Shader glow is slightly overpowering on dark tiles. Reduce intensity by 15%.',
        externalAssetUrl: 'https://shadertoy.com/view/example',
      },
      {
        id: 'rev_4',
        assetName: 'Art Room Furniture & Cintiq Displays',
        ownerName: 'Elena Rostova',
        category: 'Environment',
        reviewState: 'approved',
        progressPercentage: 100,
        feedbackNotes: 'Tablet angle and color accents approved.',
        externalAssetUrl: 'https://figma.com/@studio/assets/art-furniture',
      },
    ],
  },
  {
    id: 'obj_art_director_desk',
    name: 'Art Director Desk — Elena Rostova',
    type: 'art_director',
    x: 1195,
    y: 75,
    roomType: 'art',
    title: 'Art Direction & Supervision Desk',
    description: 'Ultrawide command desk reviewing art benchmarks, character turnarounds, and visual style guides.',
    actionText: 'Inspect Art Direction',
    artDirectorOverview: {
      directorName: 'Elena Rostova',
      roleTitle: 'Studio Art Director',
      currentVisualDirection: 'Cyberpunk Neo-Tokyo with Lo-Fi Warmth: High-contrast pixel silhouettes, vibrant neon cyan & magenta accents, handcrafted painterly textures.',
      colorPaletteKeys: ['#ec4899', '#a855f7', '#38bdf8', '#10b981', '#f59e0b'],
      activeMilestone: 'Sprint 2 — Room Aesthetics & Character Turnarounds',
      itemsWaitingReviewCount: 3,
      blockers: [
        'Pending character turnaround sign-off before animation rigging',
        'Maintain consistent 2:1 isometric ratio for room props',
      ],
    },
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Elena Rostova',
      discipline: 'Artist',
      roleTitle: 'Studio Art Director',
      isAssigned: true,
      assignedUserId: 'colleague_elena',
      isOnline: true,
      isPresentInRoom: false,
      currentGoal: 'Sprint 2 visual consistency & art direction benchmark approval',
      progressPercentage: 85,
      status: 'Reviewing PR',
      currentTaskTitle: 'Reviewing character turnaround animations and color scripts',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Figma: Art Direction Styleguide V2',
        url: 'https://figma.com/@studio/styleguide',
      },
    },
  },
  {
    id: 'obj_art_workstation_kenji',
    name: 'Workstation 1 — Kenji Sato',
    type: 'monitor',
    x: 1010,
    y: 140,
    roomType: 'art',
    title: 'Lead 2D & Character Artist Station',
    description: 'High-precision pen tablet workstation running character turnaround animations.',
    actionText: 'Inspect Kenji Sato',
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Kenji Sato',
      discipline: 'Artist',
      roleTitle: 'Lead 2D Character Artist',
      isAssigned: true,
      assignedUserId: 'colleague_kenji',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Player avatar 4-direction turnaround & idle expressions',
      progressPercentage: 80,
      status: 'In Flow',
      currentTaskTitle: 'Aseprite sprite sheet frames for 4-direction walk cycle',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Aseprite Sheet: player_turnaround.ase',
        url: 'https://figma.com/@studio/player-turnaround',
      },
    },
  },
  {
    id: 'obj_art_workstation_clara',
    name: 'Workstation 2 — Clara Oswald',
    type: 'monitor',
    x: 1140,
    y: 140,
    roomType: 'art',
    title: 'Environment & Concept Station',
    description: 'Dual display station drafting modular studio wall tilesets and neon accents.',
    actionText: 'Inspect Clara Oswald',
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Clara Oswald',
      discipline: 'Artist',
      roleTitle: 'Environment & Concept Artist',
      isAssigned: true,
      assignedUserId: 'colleague_clara',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Modular room tilesets & floor texture variations',
      progressPercentage: 65,
      status: 'Creating Concept',
      currentTaskTitle: 'Cyberpunk floor accents & room divider walls in Photoshop',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'ArtStation / Figma: studio_interior_tiles',
        url: 'https://figma.com/@studio/interior-tiles',
      },
    },
  },
  {
    id: 'obj_art_workstation_marcus',
    name: 'Workstation 3 — Marcus Vance',
    type: 'monitor',
    x: 1010,
    y: 240,
    roomType: 'art',
    title: 'Technical & VFX Station',
    description: 'Shader drafting and visual particle station (assigned to Marcus Vance, currently offline).',
    actionText: 'Inspect Marcus Vance (Offline)',
    workstationStatus: 'assigned_offline',
    workstationData: {
      name: 'Marcus Vance',
      discipline: 'Artist',
      roleTitle: 'Technical & VFX Artist',
      isAssigned: true,
      assignedUserId: 'colleague_marcus',
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Dynamic WebGL interaction pulse & glow shaders',
      progressPercentage: 90,
      status: 'Reviewing PR',
      currentTaskTitle: 'Fragment shader bloom filter for neon floor rings',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Shadertoy: Neon Pulse Shader',
        url: 'https://shadertoy.com/view/example',
      },
    },
  },
  {
    id: 'obj_art_workstation_flex',
    name: 'Workstation 4 — Flex Art Desk',
    type: 'monitor',
    x: 1140,
    y: 240,
    roomType: 'art',
    title: 'Available Art Hotdesk',
    description: 'Calibrated drawing tablet desk available for guest artists, freelancers, or sprint spikes.',
    actionText: 'Use Art Tablet Desk',
    workstationStatus: 'available',
    workstationData: {
      name: 'Available (Flex Art Desk)',
      discipline: 'Artist',
      roleTitle: 'Open Art Workstation',
      isAssigned: false,
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Open for assignment or immediate drawing session',
      progressPercentage: 0,
      status: 'Idle',
      currentTaskTitle: 'Cintiq display calibrated & ready for check-in',
      seatOffset: { x: 0, y: 19 },
    },
  },
  {
    id: 'obj_review_bench',
    name: 'Critique & Discussion Sofa',
    type: 'desk',
    x: 915,
    y: 350,
    roomType: 'art',
    title: 'Critique & Peer Review Area',
    description: 'Casual seating area for impromptu art critiques, over-the-shoulder feedback, and design syncs.',
    actionText: 'Sit & Discuss',
  },
  {
    id: 'obj_shared_cabinet_art',
    name: 'Art Supply Cabinet',
    type: 'decoration',
    x: 1190,
    y: 330,
    roomType: 'art',
    title: 'Lemari Perlengkapan Seni',
    description: 'Lemari penyimpanan tablet grafis cadangan, stylus, dan referensi material seni.',
    actionText: 'Buka Lemari Perlengkapan',
  },
  {
    id: 'obj_plant_art',
    name: 'Art Studio Plant',
    type: 'plant',
    x: 1225,
    y: 55,
    roomType: 'art',
    title: 'Tanaman Hias Studio Seni',
    description: 'Tanaman hijau indoor sebagai aksen alami di studio konsep dan animasi.',
    actionText: 'Lihat Tanaman',
  },

  // Game Design Bay — Systems, Mechanics & Pacing Lab
  {
    id: 'obj_room_layout_design',
    name: 'Console Pengatur Ruangan (Design Bay)',
    type: 'room_layout',
    x: 75,
    y: 495,
    roomType: 'design',
    title: 'Konsol Penataan Ruangan — Game Design & Narrative Bay',
    description: 'Atur posisi furniture, putar arah 4 orientasi (0°, 90°, 180°, 270°), dan kunci layout ruangan.',
    actionText: 'Atur Layout Ruangan',
  },
  {
    id: 'obj_mechanic_board',
    name: 'Gameplay Mechanics Board',
    type: 'mechanic_board',
    x: 90,
    y: 495,
    roomType: 'design',
    title: 'Gameplay Mechanics Matrix',
    description: 'Core player verbs, state machines, combos, and system interaction dependencies.',
    actionText: 'Open Mechanics Board',
    mechanicItems: [
      {
        id: 'mech_1',
        name: 'Kinetic Dash Strike',
        owner: 'Maya Lin',
        category: 'Combat',
        status: 'In Balance',
        progress: 85,
        reviewState: 'approved',
        description: 'Dash with 0.15s invulnerability that cancels into a cleaving arc strike upon enemy contact.',
      },
      {
        id: 'mech_2',
        name: 'Dynamic Parry Window',
        owner: 'Maya Lin',
        category: 'Combat',
        status: 'Prototyped',
        progress: 70,
        reviewState: 'pending',
        description: 'Perfect parry at 6-frame window staggering humanoids and reflecting energy projectiles.',
      },
      {
        id: 'mech_3',
        name: 'Wall Slide & Mantle',
        owner: 'Lucas Zhao',
        category: 'Traversal',
        status: 'Approved',
        progress: 100,
        reviewState: 'approved',
        description: 'Smooth wall cling with directional leap allowing vertical navigation in high-density sectors.',
      },
      {
        id: 'mech_4',
        name: 'Nanite Core Overclock',
        owner: 'Sarah Jenkins',
        category: 'Economy',
        status: 'In Balance',
        progress: 60,
        reviewState: 'changes_requested',
        description: 'Temporary buff increasing energy weapon fire rate by 30% at the cost of 5 Nanites per second.',
      },
      {
        id: 'mech_5',
        name: 'Branching Dialogue Trees',
        owner: 'Lucas Zhao',
        category: 'Narrative',
        status: 'In Concept',
        progress: 40,
        reviewState: 'pending',
        description: 'Conditional response choices impacted by faction alignment and acquired mission intel.',
      },
    ],
  },
  {
    id: 'obj_flow_board',
    name: 'Level & Gameplay Flow Board',
    type: 'flow_board',
    x: 90,
    y: 575,
    roomType: 'design',
    title: 'Campaign Flow & Pacing Matrix',
    description: 'Mission progression curves, level onboarding, enemy density ramps, and narrative climax gates.',
    actionText: 'Open Level Flow Board',
    flowItems: [
      {
        id: 'flow_1',
        title: 'Sector 0 — The Quarantine Zone',
        levelOrPhase: 'Phase 1: Tutorial',
        targetPacing: 'Low-to-Medium Tension',
        summary: 'Teaches movement verbs, basic collision navigation, and primary attack. Closes with a mini-enforcer confrontation.',
        coreChallenge: 'Mastering the 4-direction dodge roll',
        externalDocUrl: 'https://figma.com/@studio/campaign-flow-act1',
      },
      {
        id: 'flow_2',
        title: 'Sector 1 — Neon Underbelly',
        levelOrPhase: 'Phase 2: Exploration',
        targetPacing: 'Medium Tension & High Verticality',
        summary: 'Multi-tiered alleyways featuring platforming challenges, hidden nanite caches, and patrol stealth mechanics.',
        coreChallenge: 'Navigating laser grids and vertical wall slides',
        externalDocUrl: 'https://figma.com/@studio/campaign-flow-act1',
      },
      {
        id: 'flow_3',
        title: 'Sector 2 — Cyber-Nexus Gateway',
        levelOrPhase: 'Phase 3: Climax',
        targetPacing: 'High Tension • Boss Gate',
        summary: 'Intense gauntlet requiring combined mastery of dash-strike, projectile parry, and power management.',
        coreChallenge: 'Defeating Apex Warden in phase-changing arena',
        externalDocUrl: 'https://figma.com/@studio/campaign-flow-act1',
      },
    ],
  },
  {
    id: 'obj_balancing_board',
    name: 'Balancing & Economy Board',
    type: 'balancing_board',
    x: 345,
    y: 495,
    roomType: 'design',
    title: 'Combat & Economy Balancing Board',
    description: 'DPS benchmarks, time-to-kill metrics, enemy stat scaling, and resource drop economy tables.',
    actionText: 'Open Balancing Board',
    balancingItems: [
      {
        id: 'bal_1',
        parameterName: 'Primary Slash Base DPS',
        category: 'Player Combat',
        currentValue: '82 DPS',
        targetBaseline: '75 DPS (±5%)',
        notes: 'Currently slightly overtuned against Tier 1 grunts; reduces combat duration by 18%.',
        reviewState: 'changes_requested',
      },
      {
        id: 'bal_2',
        parameterName: 'Dash Invulnerability Frames',
        category: 'Player Combat',
        currentValue: '9 Frames (0.15s)',
        targetBaseline: '9 Frames',
        notes: 'Optimal responsive dodge feel. Tested in 60 FPS playtest sandbox.',
        reviewState: 'approved',
      },
      {
        id: 'bal_3',
        parameterName: 'Cyber-Enforcer Health Pool',
        category: 'Enemy Stats',
        currentValue: '320 HP',
        targetBaseline: '300 HP',
        notes: 'Requires 4 full combo chains to down. Pacing feels heavy and satisfying.',
        reviewState: 'approved',
      },
      {
        id: 'bal_4',
        parameterName: 'Nanite Drop Frequency per Grunt',
        category: 'Economy Drop',
        currentValue: '45% Drop Chance',
        targetBaseline: '35% Drop Chance',
        notes: 'Players accumulating excess upgrades too early in Sector 1; recommended 35% cap.',
        reviewState: 'pending',
      },
      {
        id: 'bal_5',
        parameterName: 'Boss Phase 2 Aggro Scaling',
        category: 'Difficulty Curve',
        currentValue: '1.4x Speed Multiplier',
        targetBaseline: '1.25x Speed',
        notes: 'Too punitive for keyboard-only playtesters; need telegraph duration buffed by 100ms.',
        reviewState: 'changes_requested',
      },
    ],
  },
  {
    id: 'obj_lead_designer_desk',
    name: 'Lead Designer Desk — Maya Lin',
    type: 'lead_designer',
    x: 210,
    y: 600,
    roomType: 'design',
    title: 'Systems & Combat Leadership Station',
    description: 'Command station monitoring game loop coherence, active design sprints, and core player experience pillars.',
    actionText: 'Inspect Design Leadership',
    leadDesignOverview: {
      leadName: 'Maya Lin',
      roleTitle: 'Lead Systems & Combat Designer',
      overallDesignProgress: 78,
      corePillars: [
        'Instant Mechanical Feedback',
        'Meaningful Player Expression',
        'Fair High-Skill Ceiling',
      ],
      activeDesignGoals: [
        'Refine boss stagger windows for tight rhythmic combat',
        'Finalize early-game nanite economy drop rate',
        'Lock onboarding tutorial pacing in Sector 0',
      ],
      mechanicsInReviewCount: 2,
      blockedItems: [
        'Awaiting audio hit sound effects to calibrate parry timing window',
        'Need updated collision bounding box on Enforcer shield',
      ],
    },
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Maya Lin',
      discipline: 'Game Designer',
      roleTitle: 'Lead Systems & Combat Designer',
      isAssigned: true,
      assignedUserId: 'colleague_maya',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Combat rhythm, parry window timing, and boss stagger parameters',
      progressPercentage: 85,
      status: 'In Flow',
      currentTaskTitle: 'Tuning parry vulnerability recovery frames in design sandbox',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Notion GDD: Combat System Spec V3',
        url: 'https://notion.so/studio/combat-system-spec',
      },
    },
  },
  {
    id: 'obj_design_workstation_lucas',
    name: 'Workstation 2 — Lucas Zhao',
    type: 'monitor',
    x: 300,
    y: 600,
    roomType: 'design',
    title: 'Level & Narrative Design Station',
    description: 'Dual display station mapping campaign mission layouts, encounter arenas, and dialogue consequence trees.',
    actionText: 'Inspect Lucas Zhao',
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Lucas Zhao',
      discipline: 'Game Designer',
      roleTitle: 'Level & Narrative Designer',
      isAssigned: true,
      assignedUserId: 'colleague_lucas',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Sector 1 verticality routes and pacing beat map',
      progressPercentage: 70,
      status: 'Drafting GDD',
      currentTaskTitle: 'Designing encounter arena 3 choke points and vertical traversal paths',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Miro / FigJam: Sector 1 Flow Layout',
        url: 'https://miro.com/app/board/sector-1-flow',
      },
    },
  },
  {
    id: 'obj_design_workstation_sarah',
    name: 'Workstation 3 — Sarah Jenkins',
    type: 'monitor',
    x: 210,
    y: 695,
    roomType: 'design',
    title: 'Economy & Systems Balancing Station',
    description: 'Numerical spreadsheet station modeling progression curves, currency sinks, and drop tables (currently offline).',
    actionText: 'Inspect Sarah Jenkins (Offline)',
    workstationStatus: 'assigned_offline',
    workstationData: {
      name: 'Sarah Jenkins',
      discipline: 'Game Designer',
      roleTitle: 'Economy & Systems Balancing Designer',
      isAssigned: true,
      assignedUserId: 'colleague_sarah',
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Player power progression model and nanite economy balance',
      progressPercentage: 80,
      status: 'Balancing Economy',
      currentTaskTitle: 'Calibrating weapon upgrade tiers vs chapter completion time',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Google Sheets: Progression Model V2',
        url: 'https://docs.google.com/spreadsheets/d/example',
      },
    },
  },
  {
    id: 'obj_design_workstation_flex',
    name: 'Workstation 4 — Flex Design Desk',
    type: 'monitor',
    x: 300,
    y: 695,
    roomType: 'design',
    title: 'Available Game Design Hotdesk',
    description: 'Open design workstation with game controller and GDD binder, ready for guest designer or immediate session.',
    actionText: 'Use Design Hotdesk',
    workstationStatus: 'available',
    workstationData: {
      name: 'Available (Flex Design Desk)',
      discipline: 'Game Designer',
      roleTitle: 'Open Game Design Station',
      isAssigned: false,
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Open for assignment or immediate game design session',
      progressPercentage: 0,
      status: 'Idle',
      currentTaskTitle: 'Design station calibrated & ready for check-in',
      seatOffset: { x: 0, y: 19 },
    },
  },
  {
    id: 'obj_design_discussion_table',
    name: 'Game Design Critique & Discussion Area',
    type: 'desk',
    x: 150,
    y: 785,
    roomType: 'design',
    title: 'Design Critique & Brainstorm Table',
    description: 'Collaborative coffee table with interactive holographic pad for mission flow reviews and mechanic feedback.',
    actionText: 'Sit & Brainstorm',
  },
  {
    id: 'obj_arcade_cabinet',
    name: 'Playtest Arcade Station',
    type: 'arcade',
    x: 345,
    y: 780,
    roomType: 'design',
    title: 'Studio Playtest Cabinet',
    description: 'Internal testing sandbox for controller feel, input responsiveness, and game latency.',
    actionText: 'Launch Playtest Session',
  },
  {
    id: 'obj_shared_shelf_design',
    name: 'Game Design Archive Shelf',
    type: 'decoration',
    x: 245,
    y: 490,
    roomType: 'design',
    title: 'Rak Arsip & Buku Desain Game',
    description: 'Koleksi Game Design Document klasik, papan permainan analog, dan studi naratif.',
    actionText: 'Buka Arsip Desain',
  },
  {
    id: 'obj_plant_design_nw',
    name: 'Design Bay Plant (North)',
    type: 'plant',
    x: 55,
    y: 480,
    roomType: 'design',
    title: 'Tanaman Hias Design Bay (Utara)',
    description: 'Tanaman hias untuk menciptakan suasana kerja kreatif.',
    actionText: 'Lihat Tanaman',
  },
  {
    id: 'obj_plant_design_se',
    name: 'Design Bay Plant (South)',
    type: 'plant',
    x: 385,
    y: 820,
    roomType: 'design',
    title: 'Tanaman Hias Design Bay (Selatan)',
    description: 'Tanaman hias penyegar di sudut playtest arcade.',
    actionText: 'Lihat Tanaman',
  },

  // Audio & Sound Studio — Dedicated Audio Production & Listening Lab
  {
    id: 'obj_room_layout_audio',
    name: 'Console Pengatur Ruangan (Audio Studio)',
    type: 'room_layout',
    x: 1205,
    y: 495,
    roomType: 'audio',
    title: 'Konsol Penataan Ruangan — Audio & Sound Studio',
    description: 'Atur posisi furniture, putar arah 4 orientasi (0°, 90°, 180°, 270°), dan kunci layout ruangan.',
    actionText: 'Atur Layout Ruangan',
  },
  {
    id: 'obj_audio_direction_board',
    name: 'Audio Direction & Blueprint Board',
    type: 'audio_direction',
    x: 935,
    y: 490,
    roomType: 'audio',
    title: 'Audio Direction & Aesthetic Blueprint',
    description: 'Music styleguides, ambient soundscapes, transient profiles, and sprint audio blockers.',
    actionText: 'Open Audio Blueprint',
    audioDirectionData: {
      musicDirection:
        'Dark hybrid synth-orchestral with reactive stems (Exploring, Low Tension, Climax Boss). Analog warmth with punchy digital transients.',
      ambienceDirection:
        'Layered industrial cyberpunk soundscapes. Wet asphalt reflections, subtle HVAC air circulation, neon capacitor buzz, and distant sector rail hums.',
      sfxStyle:
        'Physical, weighty kinetic impacts. High transient punch with metallic resonance and short, crisp sub-bass tail.',
      currentPriorities: [
        'Finalize combat transition stems for Sector 0 mini-boss',
        'Surface-aware player footsteps (metal grating, wet concrete, puddles)',
        'Synthesize holographic UI confirmation chirps and parry impact spike',
      ],
      blockedItems: [
        'Awaiting boss phase 2 animation timings to lock musical crescendo hits',
        'Need collision audio triggers placed in Sector 1 sewer tunnels',
      ],
      audioEngineStack: 'FMOD Studio 2.02 + WebAudio / Phaser Sound Subsystem',
      guidelines: [
        'Mix target baseline: -14 LUFS integrated for music, -6 dB peak headroom for combat SFX',
        'All continuous ambient loops must have seamless zero-crossing loop points',
        'Prioritize sidechain ducking on low-end frequencies when dialogue or critical parry cues play',
      ],
    },
  },
  {
    id: 'obj_audio_listening_station',
    name: 'Audio Review & Listening Station',
    type: 'audio_listening',
    x: 1175,
    y: 495,
    roomType: 'audio',
    title: 'Studio Listening & Audio Review Console',
    description: 'Calibrated reference monitors, dynamic stem inspection, and review approvals queue.',
    actionText: 'Open Listening Console',
    listeningItems: [
      {
        id: 'rev_aud_1',
        title: 'Combat Stems — Sector 0 Mini-Boss Crescendo',
        category: 'Music',
        author: 'Elena Rostova',
        duration: '02:45',
        status: 'Awaiting Feedback',
        reviewState: 'pending',
        waveformProfile: [25, 40, 65, 80, 55, 70, 95, 85, 60, 45, 75, 90, 100, 60, 40],
        feedbackNotes:
          'Needs sidechain ducking test with player kinetic dash and parry sound effects. Ensure percussion does not mask high-frequency cues.',
        tags: ['combat', 'dynamic-stems', '140bpm', 'hybrid-orchestral'],
      },
      {
        id: 'rev_aud_2',
        title: 'Player Surface Footsteps (Metal Grate & Wet Asphalt)',
        category: 'SFX',
        author: 'Taro Tanaka',
        duration: '00:38',
        status: 'Revision Submitted',
        reviewState: 'pending',
        waveformProfile: [20, 85, 30, 90, 25, 75, 20, 80, 15, 70, 20, 85, 25, 60, 20],
        feedbackNotes:
          'Re-recorded with lighter heel impacts and reduced sub-bass rumbling. 6 randomized round-robin variations per surface.',
        tags: ['foley', 'footsteps', 'player-verbs', 'round-robin'],
      },
      {
        id: 'rev_aud_3',
        title: 'Cyber-Enforcer Heavy Shield Charge & Impact',
        category: 'SFX',
        author: 'Taro Tanaka',
        duration: '00:14',
        status: 'Final Mix Check',
        reviewState: 'approved',
        waveformProfile: [30, 45, 60, 80, 95, 100, 70, 40, 30, 20, 15, 10, 5, 2, 0],
        feedbackNotes:
          'Excellent weighty metallic resonance. Tested against player shield parry; feedback clarity is sharp and punchy.',
        tags: ['combat', 'enemy-sfx', 'impact', 'approved'],
      },
      {
        id: 'rev_aud_4',
        title: 'Sector 1 Neon Underbelly Ambient Drone & HVAC Hum',
        category: 'Ambience',
        author: 'Julian Vance',
        duration: '03:12',
        status: 'Awaiting Feedback',
        reviewState: 'pending',
        waveformProfile: [40, 45, 42, 48, 44, 46, 50, 48, 45, 43, 46, 48, 45, 42, 40],
        feedbackNotes:
          'Seamless quad-surround loop test. Reverb decay set to 1.8s for alleyway corridors with wet high-pass filter.',
        tags: ['environment', 'ambient-loop', 'reverb', 'immersive'],
      },
    ],
  },
  {
    id: 'obj_lead_audio_desk',
    name: 'Lead Audio Console — Julian Vance',
    type: 'lead_audio',
    x: 980,
    y: 605,
    roomType: 'audio',
    title: 'Audio Direction & Mixing Console',
    description: 'Audio director command station monitoring stem balance, audio middleware, and overall audio progress.',
    actionText: 'Inspect Audio Leadership',
    leadAudioOverview: {
      leadName: 'Julian Vance',
      roleTitle: 'Audio Director & Lead Sound Designer',
      overallAudioProgress: 82,
      pillarAesthetics: [
        'Modular Stem Mixing',
        'High-Impact Physical Transients',
        'Diegetic Environmental Immersion',
      ],
      activeAudioGoals: [
        'Balance combat music volume sidechain vs parry SFX spikes',
        'Master Sector 0 boss phase transition crescendos',
        'Implement footstep material switch surface detection',
        'Calibrate headphone virtual 3D surround sound spatializer',
      ],
      itemsWaitingReviewCount: 3,
      blockedItems: [
        'Awaiting audio hit markers from animation department for kinetic dash strike',
        'Need updated reverb volume bounding box for Sector 1 sewer junction',
      ],
    },
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Julian Vance',
      discipline: 'Audio',
      roleTitle: 'Audio Director & Lead Sound Designer',
      isAssigned: true,
      assignedUserId: 'colleague_julian',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Dynamic combat music sidechaining and boss transition crescendos',
      progressPercentage: 85,
      status: 'Audio Mixing',
      currentTaskTitle: 'Calibrating sidechain compressor attack times on FMOD master bus',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'FMOD Studio Project: Master_Session_V2',
        url: 'https://fmod.example-studio.internal/projects/master',
      },
    },
  },
  {
    id: 'obj_music_desk',
    name: 'Music Workstation — Elena Rostova',
    type: 'music_workstation',
    x: 1090,
    y: 605,
    roomType: 'audio',
    title: 'Music Composition & Synthesis Station',
    description: 'Dual monitor MIDI workstation drafting dynamic combat stems and exploration themes.',
    actionText: 'Inspect Elena Rostova',
    musicTracks: [
      {
        id: 'trk_1',
        trackName: 'Neon City Infiltration — Stealth Theme',
        owner: 'Elena Rostova',
        progress: 90,
        status: 'Mixing',
        reviewState: 'approved',
        duration: '03:24',
        bpm: 124,
        category: 'Exploration',
        notes: 'Low-tension ambient synth layers with analog filter sweeps. Stems split into Rhythm, Bass, Lead, and Pad.',
        externalUrl: 'https://soundcloud.com/example/stealth-theme',
      },
      {
        id: 'trk_2',
        trackName: 'Sector 0 Mini-Boss — Kinetic Clash',
        owner: 'Elena Rostova',
        progress: 85,
        status: 'Arranging',
        reviewState: 'pending',
        duration: '02:48',
        bpm: 142,
        category: 'Combat',
        notes: 'High-intensity dynamic combat loops. Features 3-tier layering triggered by enemy aggro levels.',
        externalUrl: 'https://soundcloud.com/example/kinetic-clash',
      },
      {
        id: 'trk_3',
        trackName: 'Quarantine Gate Climax — Heavy Orchestral Climax',
        owner: 'Elena Rostova',
        progress: 60,
        status: 'Composing',
        reviewState: 'changes_requested',
        duration: '04:10',
        bpm: 130,
        category: 'Boss',
        notes: 'Director requested more brass presence and heavier sub-bass hits for phase 2 transition.',
        externalUrl: 'https://soundcloud.com/example/boss-climax',
      },
      {
        id: 'trk_4',
        trackName: 'Main Title & Studio Boot Theme',
        owner: 'Elena Rostova',
        progress: 100,
        status: 'Mastered',
        reviewState: 'approved',
        duration: '01:50',
        bpm: 110,
        category: 'Menu',
        notes: 'Mastered to -14 LUFS integrated. Clean loop points for main menu screen.',
        externalUrl: 'https://soundcloud.com/example/title-theme',
      },
    ],
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Elena Rostova',
      discipline: 'Audio',
      roleTitle: 'Lead Composer & Synthesist',
      isAssigned: true,
      assignedUserId: 'colleague_elena',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Sector 0 boss fight reactive musical stems and combat tension curve',
      progressPercentage: 80,
      status: 'Scoring',
      currentTaskTitle: 'Recording analog synthesizer bass arpeggios in Ableton Live',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Ableton Session: Sector0_Combat_Stems.als',
        url: 'https://ableton.example-studio.internal/projects/sector0',
      },
    },
  },
  {
    id: 'obj_sfx_desk',
    name: 'SFX & Foley Station — Taro Tanaka',
    type: 'sfx_workstation',
    x: 980,
    y: 695,
    roomType: 'audio',
    title: 'SFX & Foley Sound Design Station',
    description: 'Microphone foley recording and synthesis station designing weapon impacts and surface footsteps.',
    actionText: 'Inspect Taro Tanaka',
    sfxItems: [
      {
        id: 'sfx_1',
        sfxName: 'Player Surface Footsteps (6-Step Round Robin)',
        category: 'Footsteps',
        owner: 'Taro Tanaka',
        progress: 95,
        status: 'In Game Ready',
        variationCount: 18,
        reviewState: 'approved',
        notes: 'Recorded across metal grating, wet tarmac, and concrete. Integrated into player walk cycle triggers.',
      },
      {
        id: 'sfx_2',
        sfxName: 'Kinetic Dash Strike Impact & Whoosh',
        category: 'Weapons',
        owner: 'Taro Tanaka',
        progress: 90,
        status: 'Mastering',
        reviewState: 'approved',
        notes: 'Crisp transient attack with analog synthesizer sub-bass drop on hit confirm.',
      },
      {
        id: 'sfx_3',
        sfxName: 'Perfect Parry Timing & Projectile Reflection Clink',
        category: 'Weapons',
        owner: 'Taro Tanaka',
        progress: 80,
        status: 'Synthesizing',
        reviewState: 'pending',
        notes: 'Glassy high-frequency chime to clearly signal parry window success amidst busy combat mix.',
      },
      {
        id: 'sfx_4',
        sfxName: 'Holographic Terminal Open, Select, & Back Bleeps',
        category: 'UI',
        owner: 'Taro Tanaka',
        progress: 100,
        status: 'In Game Ready',
        variationCount: 12,
        reviewState: 'approved',
        notes: 'Subtle, tactile UI chirps designed to never cause auditory fatigue during inventory management.',
      },
      {
        id: 'sfx_5',
        sfxName: 'Rain On Glass & Distant Sector Transformer Hum',
        category: 'Ambience',
        owner: 'Taro Tanaka',
        progress: 85,
        status: 'Mastering',
        reviewState: 'pending',
        notes: 'Continuous 4-channel ambient loop with randomized raindrop burst triggers.',
      },
      {
        id: 'sfx_6',
        sfxName: 'Cyber-Hound Aggro Growl & Mechanical Panting',
        category: 'Creatures',
        owner: 'Taro Tanaka',
        progress: 70,
        status: 'Recording',
        reviewState: 'pending',
        notes: 'Hybrid lion roar combined with pneumatic servo motor whine for Sector 1 patrol beasts.',
      },
    ],
    workstationStatus: 'assigned_active',
    workstationData: {
      name: 'Taro Tanaka',
      discipline: 'Audio',
      roleTitle: 'Senior Foley & Sound Designer',
      isAssigned: true,
      assignedUserId: 'colleague_taro',
      isOnline: true,
      isPresentInRoom: true,
      currentGoal: 'Kinetic weapon impact transients and player surface footstep audio',
      progressPercentage: 88,
      status: 'Mastering SFX',
      currentTaskTitle: 'Editing 6-step round-robin foley takes in Reaper',
      seatOffset: { x: 0, y: 19 },
      externalWorkLink: {
        label: 'Reaper Project: Combat_SFX_Pack_V1',
        url: 'https://reaper.example-studio.internal/projects/combat-sfx',
      },
    },
  },
  {
    id: 'obj_audio_workstation_flex',
    name: 'Workstation 4 — Flex Audio Desk',
    type: 'monitor',
    x: 1090,
    y: 695,
    roomType: 'audio',
    title: 'Available Audio Hotdesk',
    description: 'Calibrated audio interface station ready for guest sound designers, vocalists, or sprint spikes.',
    actionText: 'Use Audio Hotdesk',
    workstationStatus: 'available',
    workstationData: {
      name: 'Available (Flex Audio Desk)',
      discipline: 'Audio',
      roleTitle: 'Open Sound Design Station',
      isAssigned: false,
      isOnline: false,
      isPresentInRoom: false,
      currentGoal: 'Open for audio assignment or immediate recording session',
      progressPercentage: 0,
      status: 'Idle',
      currentTaskTitle: 'Preamp & audio interface calibrated & ready for session check-in',
      seatOffset: { x: 0, y: 19 },
    },
  },
  {
    id: 'obj_audio_discussion_table',
    name: 'Acoustic Review & Discussion Area',
    type: 'desk',
    x: 980,
    y: 785,
    roomType: 'audio',
    title: 'Acoustic Discussion & Review Table',
    description: 'Collaborative listening table with holographic soundboard for stem critiques and milestone listening.',
    actionText: 'Sit & Review Audio',
  },
  {
    id: 'obj_audio_surround_array',
    name: 'Surround Sound Monitor Stack',
    type: 'arcade',
    x: 1195,
    y: 780,
    roomType: 'audio',
    title: 'Surround Sound Monitor Array',
    description: 'High-end studio reference monitor stack testing 3D spatial audio, surround panning, and sub-bass response.',
    actionText: 'Test Spatial Audio',
  },
  {
    id: 'obj_shared_cabinet_audio',
    name: 'Audio Gear Cabinet',
    type: 'decoration',
    x: 1080,
    y: 490,
    roomType: 'audio',
    title: 'Lemari Peralatan Audio',
    description: 'Lemari instrumen mikrofon Foley, headphone cadangan, dan kabel audio profesional.',
    actionText: 'Periksa Peralatan Audio',
  },
  {
    id: 'obj_plant_audio_nw',
    name: 'Audio Studio Plant (North)',
    type: 'plant',
    x: 890,
    y: 480,
    roomType: 'audio',
    title: 'Tanaman Akustik Audio (Utara)',
    description: 'Tanaman indoor berdaun lebar penyerap pantulan suara di studio audio.',
    actionText: 'Lihat Tanaman',
  },
  {
    id: 'obj_plant_audio_se',
    name: 'Audio Studio Plant (South)',
    type: 'plant',
    x: 1220,
    y: 820,
    roomType: 'audio',
    title: 'Tanaman Akustik Audio (Selatan)',
    description: 'Tanaman indoor penyegar suasana lounge audio.',
    actionText: 'Lihat Tanaman',
  },

  // Conference & Strategy Hub (Meeting Room)
  {
    id: 'obj_room_layout_meeting',
    name: 'Console Pengatur Ruangan (Conference Hub)',
    type: 'room_layout',
    x: 480,
    y: 75,
    roomType: 'meeting',
    title: 'Konsol Penataan Ruangan — Conference & Strategy Hub',
    description: 'Atur posisi furniture, putar arah 4 orientasi (0°, 90°, 180°, 270°), dan kunci layout ruangan.',
    actionText: 'Atur Layout Ruangan',
  },
  {
    id: 'obj_presentation_screen',
    name: 'Shared Presentation Screen',
    type: 'presentation_screen',
    x: 640,
    y: 72,
    roomType: 'meeting',
    title: 'Shared Conference Display',
    description: 'Ultrawide shared projection display for milestone decks, Figma canvases, and sprint reviews.',
    actionText: 'Lihat Layar Presentasi Bersama',
    presentationScreenData: {
      deckTitle: 'Studio All-Hands: Sprint 14 & Alpha Readiness',
      activeSlideIndex: 0,
      presenterName: 'Alex Rivera (Lead Designer)',
      slides: [
        {
          id: 'slide_1',
          slideNumber: 1,
          title: 'Milestone 2: Core Gameplay Loop & Sector 0 Alpha Readiness',
          subtitle: 'Sprint 14 All-Hands Cross-Discipline Sync',
          type: 'slide',
          contentPreview:
            'Ikhtisar penyelesaian sprint 14 menuju Alpha Milestone. Pembahasan sinkronisasi antardivisi Programming, Art, Design, dan Audio untuk playtest internal pertama.',
          bulletPoints: [
            'Programming: Movement physics, interaction trigger system, dan room bounds terselesaikan.',
            'Art: 100% environment room tileset, workstation assets, dan avatar walk cycle terintegrasi.',
            'Design: Core combat loop spec, pacing curve, dan prototype balance sheet selesai.',
            'Audio: Dynamic combat stems, directional sound fx, dan ambient background loop aktif.',
          ],
          metrics: [
            { label: 'Sprint Velocity', value: '94%' },
            { label: 'Alpha Target', value: 'Oct 24' },
            { label: 'Open Blockers', value: '2 Medium' },
          ],
        },
        {
          id: 'slide_2',
          slideNumber: 2,
          title: 'Figma Canvas: Combat HUD & Tactical Inventory UX',
          subtitle: 'Wireframes & Interactive Prototype Spec v2.4',
          type: 'figma',
          contentPreview:
            'Desain antarmuka HUD minimalis dengan indikator status staminabar, quick-slot item radial dial, dan clean minimap overlay tanpa mengurangi pandangan visual aksi pemain.',
          bulletPoints: [
            'Penyederhanaan floating health bars untuk musuh bertipe swarm.',
            'Contrast ratio compliance (WCAG AAA) pada font status HUD.',
            'Layout respon terhadap resolusi 16:9 dan ultrawide 21:9.',
          ],
          metrics: [
            { label: 'Figma Components', value: '48 Variants' },
            { label: 'Prototype Screens', value: '12 Flows' },
            { label: 'Design Sign-off', value: 'Approved' },
          ],
          externalUrl: 'https://figma.com/@project-game/tactical-hud-v2',
        },
        {
          id: 'slide_3',
          slideNumber: 3,
          title: 'Sprint 14 Cross-Discipline Progress & QA Velocity',
          subtitle: 'Grafik Penyelesaian Task & Stabilitas Build',
          type: 'report',
          contentPreview:
            'Laporan performa build Alpha 0.4.2 menunjukkan penurunan crash-rate hingga 0.02% per 100 sesi playtest. Tidak ada blocker kritis pada loop game inti.',
          bulletPoints: [
            'Programming PR throughput meningkat 22% dibanding Sprint 13.',
            'Penyelarasan audio latency ke batas aman di bawah 18ms.',
            'Texture budget art asset optimal pada rentang VRAM 1.2 GB.',
          ],
          metrics: [
            { label: 'Build Pass Rate', value: '99.4%' },
            { label: 'Avg FPS (Target 60)', value: '59.8 fps' },
            { label: 'Resolved Tickets', value: '41 / 44' },
          ],
          externalUrl: 'https://github.com/project-studio/game/pulls',
        },
        {
          id: 'slide_4',
          slideNumber: 4,
          title: 'Design Spec: Boss Encounter Pacing & Audio Cues',
          subtitle: 'Dokumentasi Mekanik & Kordinasi Audio-Visual',
          type: 'document',
          contentPreview:
            'Spesifikasi transisi fase boss dari Phase 1 (Melee Telegraphed) menuju Phase 2 (Bullet Wave & Sound Distortion) dengan penanda suara 650ms sebelum serangan.',
          bulletPoints: [
            'Phase 1: Kecepatan serangan terprediksi dengan partikel peringatan kuning.',
            'Phase 2: Musik beralih ke layer perkusi cepat (150 BPM) dan lampu arena meredup.',
            'Phase 3: Enrage timer memicu audio alarm frekuensi tinggi.',
          ],
          metrics: [
            { label: 'Telegraph Time', value: '650 ms' },
            { label: 'Phase Count', value: '3 Phases' },
            { label: 'Audio Tracks', value: '3 Stems' },
          ],
          externalUrl: 'https://notion.so/project-studio/boss-encounter-spec',
        },
      ],
    },
  },
  {
    id: 'obj_meeting_board',
    name: 'Meeting Agenda & Decisions Board',
    type: 'meeting_board',
    x: 505,
    y: 72,
    roomType: 'meeting',
    title: 'Papan Notulensi & Agenda Rapat',
    description: 'Papan kolaborasi jadwal pembahasan, kesepakatan keputusan, dan penugasan tindak lanjut tim.',
    actionText: 'Buka Notulensi & Agenda Rapat',
    meetingSessionData: {
      meetingTitle: 'Papan Agenda & Notulensi Rapat Studio',
      leaderName: 'Alex Rivera',
      currentTopic: 'Alpha Milestone Review & Audio Sync',
      startedAt: '10:00 AM',
      participants: [
        { name: 'Alex Rivera', role: 'Lead Game Designer (Host)', discipline: 'Game Designer', status: 'speaking' },
        { name: 'Devon Vance', role: 'Lead Programmer', discipline: 'Programmer', status: 'present' },
        { name: 'Maya Lin', role: 'Lead Concept Artist', discipline: 'Artist', status: 'present' },
        { name: 'Julian Vance', role: 'Lead Audio Engineer', discipline: 'Audio', status: 'present' },
        { name: 'Elena Rostova', role: 'Senior Composer', discipline: 'Audio', status: 'remote' },
        { name: 'Sarah Chen', role: 'Systems Programmer', discipline: 'Programmer', status: 'present' },
      ],
      agenda: [
        { id: 'ag_1', time: '10:00 - 10:15', topic: 'Review Capaian Sprint 14 & Alpha Milestone Checklist', presenter: 'Alex Rivera (Lead Designer)', status: 'done' },
        { id: 'ag_2', time: '10:15 - 10:35', topic: 'Penyelarasan Collision & Movement Bounds di Seluruh Ruangan', presenter: 'Devon Vance (Lead Programmer)', status: 'done' },
        { id: 'ag_3', time: '10:35 - 10:55', topic: 'Integrasi Dynamic Combat Audio Stems dengan Partikel Visual FX', presenter: 'Julian Vance & Maya Lin', status: 'active' },
        { id: 'ag_4', time: '10:55 - 11:15', topic: 'Alokasi Kursi Meeting Multi-Avatars & Arsitektur Realtime Sinkronisasi', presenter: 'Tim Studio Core', status: 'upcoming' },
        { id: 'ag_5', time: '11:15 - 11:30', topic: 'Q&A, Action Items Assignment, dan Penjadwalan Playtest Bersama', presenter: 'Seluruh Tim', status: 'upcoming' },
      ],
      decisions: [
        { id: 'dec_1', title: 'Pemberlakuan Batas Ruang Simetris 3x2 (384x392 per Ruangan)', outcome: 'Seluruh 6 ruangan (Programming, Art, Design, Audio, Meeting, Plaza) mengadopsi dimensi dan lorong 64px seragam untuk mencegah bug tabrakan kamera.', decidedBy: 'Lead Designer & Lead Programmer' },
        { id: 'dec_2', title: 'Desain Kursi Meja Rapat Non-Konflik (Single Occupancy per Seat)', outcome: 'Setiap kursi meja rapat memiliki ID kursi unik. Pemain yang mendekati kursi dapat duduk dan status kursi berubah visual sehingga avatar lain tidak menimpa.', decidedBy: 'Alex Rivera' },
        { id: 'dec_3', title: 'Format Audio Stems 4-Layer Dinamis', outcome: 'Combat music dipecah menjadi 4 layer (Kick, Bass, Melody, Percussion) yang volume-nya beradaptasi secara dinamis dengan status pertempuran pemain.', decidedBy: 'Julian Vance' },
      ],
      actionItems: [
        { id: 'act_1', task: 'Finalisasi collider lorong pintu tengah antara Plaza dan Meeting Room', assignee: 'Devon Vance', deadline: 'Hari ini, 17:00', status: 'completed' },
        { id: 'act_2', task: 'Sinkronisasi visual kursi terisi (occupied) saat avatar duduk di meja rapat', assignee: 'Devon Vance & Alex Rivera', deadline: 'Besok, 12:00', status: 'in_progress' },
        { id: 'act_3', task: 'Eksport moodboard & palet warna UI Meeting ke format SVG Figma', assignee: 'Maya Lin', deadline: 'Kamis, 15:00', status: 'pending' },
        { id: 'act_4', task: 'Benchmarking audio memory footprint pada browser mobile/tablet', assignee: 'Julian Vance', deadline: 'Jumat, 18:00', status: 'pending' },
      ],
    },
  },
  {
    id: 'obj_project_summary_board',
    name: 'Project Summary & Milestone Board',
    type: 'project_summary_board',
    x: 775,
    y: 72,
    roomType: 'meeting',
    title: 'Project Summary & Milestone Board',
    description: 'Papan ikhtisar status capaian milestone proyek, progres 4 departemen, dan daftar kendala aktif.',
    actionText: 'Lihat Ringkasan Proyek & Blockers',
    projectSummaryData: {
      projectName: 'Cyberpunk Odyssey: Protocol Zero',
      currentMilestone: 'Milestone 2 — Core Combat & Alpha Playtest',
      targetReleaseDate: '24 Oktober 2026',
      overallProgress: 76,
      activeGoals: [
        { department: 'Programming', goal: 'Sistem pergerakan avatar, bounds collision map, & room detection realtime', progress: 92, owner: 'Devon Vance' },
        { department: 'Art', goal: 'Environment visual meeting room, sound studio tiles, & lighting accents', progress: 85, owner: 'Maya Lin' },
        { department: 'Design', goal: 'Balancing curve boss encounter & integrasi spec multi-room interaction', progress: 78, owner: 'Alex Rivera' },
        { department: 'Audio', goal: 'Mixing dynamic combat stems & surround acoustic room ambiance', progress: 72, owner: 'Julian Vance' },
      ],
      blockers: [
        { id: 'blk_1', title: 'Player camera jitter saat melewati batas lorong simetris di frame rate rendah', severity: 'medium', department: 'Programming' },
        { id: 'blk_2', title: 'Normal map art asset pada monitor meeting screen memerlukan optimasi VRAM', severity: 'medium', department: 'Art' },
      ],
      waitingReview: [
        { id: 'rev_1', item: 'PR #124: Multi-Seat Interactive Reservation System', submittedBy: 'Devon Vance', type: 'Code PR' },
        { id: 'rev_2', item: 'Sector 0 Boss Encounter Soundtrack (4 Stems Mastered)', submittedBy: 'Elena Rostova', type: 'Audio Track' },
        { id: 'rev_3', item: 'Design Document: Interactive Table Seating UX v1.2', submittedBy: 'Alex Rivera', type: 'Design Spec' },
        { id: 'rev_4', item: '3D High-Poly Turret Concept & Texture Sheet', submittedBy: 'Kai Tanaka', type: 'Art Asset' },
      ],
    },
  },
  {
    id: 'obj_meeting_podium',
    name: 'Meeting Leader Podium',
    type: 'meeting_leader',
    x: 540,
    y: 120,
    roomType: 'meeting',
    title: 'Podium Moderator Rapat',
    description: 'Podium kontrol pembicara dengan mikrofon dan kendali alur agenda rapat studio.',
    actionText: 'Masuk ke Podium Moderator',
  },
  {
    id: 'obj_large_meeting_table',
    name: 'Central Conference Table',
    type: 'meeting_table',
    x: 640,
    y: 235,
    roomType: 'meeting',
    title: 'Meja Rapat Konferensi',
    description: 'Meja rapat oval besar dengan sistem mikrofon dan pod kolaborasi laptop terintegrasi.',
    actionText: 'Lihat Meja Konferensi & Peserta',
    meetingSeats: [
      { id: 'seat_1', seatIndex: 1, x: 595, y: 185, facing: 'down', occupiedBy: 'colleague_devon', occupantName: 'Devon Vance', occupantDiscipline: 'Programmer' },
      { id: 'seat_2', seatIndex: 2, x: 685, y: 185, facing: 'down', occupiedBy: null },
      { id: 'seat_3', seatIndex: 3, x: 595, y: 285, facing: 'up', occupiedBy: null },
      { id: 'seat_4', seatIndex: 4, x: 685, y: 285, facing: 'up', occupiedBy: 'colleague_maya', occupantName: 'Maya Lin', occupantDiscipline: 'Artist' },
      { id: 'seat_5', seatIndex: 5, x: 550, y: 235, facing: 'right', occupiedBy: null },
      { id: 'seat_6', seatIndex: 6, x: 730, y: 235, facing: 'left', occupiedBy: null },
    ],
  },
  {
    id: 'obj_meeting_lounge_sofa',
    name: 'Pre-Meeting Discussion Sofa',
    type: 'desk',
    x: 495,
    y: 365,
    roomType: 'meeting',
    title: 'Sofa Diskusi Santai Pra-Rapat',
    description: 'Area duduk santai untuk obrolan santai dan penyelarasan informal sebelum agenda resmi.',
    actionText: 'Duduk & Diskusi Santai',
  },
  {
    id: 'obj_meeting_coffee_cart',
    name: 'Meeting Refreshment Bar',
    type: 'coffee',
    x: 785,
    y: 365,
    roomType: 'meeting',
    title: 'Meeting Refreshment Bar',
    description: 'Minuman dan espresso hangat untuk menjaga fokus tim selama sesi diskusi.',
    actionText: 'Ambil Espresso / Air',
  },
  {
    id: 'obj_floor_lamp_meeting',
    name: 'Conference Floor Lamp',
    type: 'decoration',
    x: 540,
    y: 360,
    roomType: 'meeting',
    title: 'Lampu Lantai Konferensi',
    description: 'Lampu berdiri hangat untuk pencahayaan ambient ruang diskusi rapat.',
    actionText: 'Lihat Lampu Konferensi',
  },
  {
    id: 'obj_plant_meeting_nw',
    name: 'Conference Plant (North)',
    type: 'plant',
    x: 470,
    y: 55,
    roomType: 'meeting',
    title: 'Tanaman Hias Konferensi (Barat Laut)',
    description: 'Tanaman hias elegan di ruang rapat direksi dan tim.',
    actionText: 'Lihat Tanaman',
  },
  {
    id: 'obj_plant_meeting_ne',
    name: 'Conference Plant (East)',
    type: 'plant',
    x: 810,
    y: 55,
    roomType: 'meeting',
    title: 'Tanaman Hias Konferensi (Timur Laut)',
    description: 'Tanaman hias elegan di sudut ruang presentasi.',
    actionText: 'Lihat Tanaman',
  },
];


// Approach from the clear side where neighboring furniture or perimeter walls
// prevent the shared asset's default south-facing interaction point.
const interactionOverrides: Record<string, { x: number; y: number }> = {
  obj_plaza_lounge_bench_left: { x: -52, y: 0 },
  obj_plaza_lounge_bench_right: { x: -52, y: 0 },
  obj_future_qa_portal: { x: 0, y: -40 },
  obj_code_whiteboard: { x: -50, y: 0 },
};

export const INTERACTIVE_OBJECTS = objects.map(object => {
  const asset = getObjectAsset(object);
  return { ...object, assetKey: asset.key, interactionOffset: interactionOverrides[object.id] ?? asset.interactionOffset, width: asset.width, height: asset.height };
});

// Shared props are now fully integrated as movable INTERACTIVE_OBJECTS
export const SHARED_DECORATIONS: Array<{ assetKey: string; x: number; y: number }> = [];
